---
- name: Dependencies are installed on Fedora
  dnf:
    state: installed
    name: "{{item}}"
  with_items:
  - "@c-development"
  - openssl
  - openssl-devel
  - libffi-devel
  - python-setuptools
  - python-virtualenv
  - libjpeg-turbo-devel
  - libjpeg-turbo
  - postgresql-devel
  when: ansible_distribution == 'Fedora' 

- name: Dependencies are installed on Debian
  apt:
    state: installed
    name: "{{item}}"
  with_items:
  - openssl
  - libffi-dev
  - python-setuptools
  - python-virtualenv
  - virtualenv
  - libjpeg-turbo8-dev
  - libjpeg-turbo8
  - libpq-dev
  - libpython2.7-dev
  when: ansible_os_family == 'Debian' 

- name: Synapse user exists
  user:
    name: synapse
    system: yes

- name: Install setuptools
  pip:
    state: latest
    virtualenv: ~/.synapse
    name: "{{item}}"
    extra_args: --process-dependency-links
  with_items:
    - setuptools
    - psycopg2
  sudo_user: synapse

- name: Synapse already installed
  shell: source ./bin/activate && pip list
  args:
    chdir: /home/synapse/.synapse
    executable: /bin/bash
  sudo_user: synapse
  register: pip_modules

- name: Synapse is installed
  pip:
    state: latest
    virtualenv: ~/.synapse
    name: "{{item}}"
    extra_args: --process-dependency-links
  with_items:
    - 'https://github.com/matrix-org/synapse/tarball/{{matrix_version}}'
  notify: restart synapse
  sudo_user: synapse
  when: pip_modules.stdout.find('matrix-synapse') == -1

- name: Synapse keys exist
  shell: source ./bin/activate && python -m synapse.app.homeserver  --server-name {{matrix_domain}}  --config-path homeserver.yaml  --generate-config --report-stats=no
  args:
    chdir: /home/synapse/.synapse
    creates: /home/synapse/.synapse/{{matrix_domain}}.tls.crt
    executable: /bin/bash
  sudo_user: synapse

- name: Synapse configuration exists
  template:
    src: homeserver.yaml.j2
    dest: /home/synapse/.synapse/homeserver.yaml

- name: Synapse systemd job is installed
  template:
    src: synapse.service.j2
    dest: /etc/systemd/system/synapse.service
  notify:
    - reload systemd
    - restart synapse
