---
- name: Dependencies are installed
  dnf:
    state: installed
    name: "{{item}}"
  with_items:
  - "@c-development"
  - openssl
  - openssl-devel
  - libffi-devel
  - python-setuptools
  - python-virtualenv
  - libjpeg-turbo-devel
  - libjpeg-turbo
  - postgresql-devel

- name: Synapse user exists
  user:
    name: synapse
    system: yes

- name: Start postgres
  service:
    name: postgresql
    state: running
    enabled: yes

- name: Synapse Postgres user exists
  postgresql_user:
    name: "{{matrix_db_user}}"
    password: "{{matrix_db_pass}}"

- name: Synapse Postgres database exists
  postgresql_db:
    encoding: UTF8
    lc_collate: C
    lc_ctype: C
    name: synapse
    owner: synapse
    template: template0

- name: Synapse is installed
  pip:
    state: latest
    virtualenv: ~/.synapse
    name: "{{item}}"
    extra_args: --process-dependency-links
  with_items:
    - setuptools
    - psycopg2
    - https://github.com/matrix-org/synapse/tarball/master
  notify: restart synapse
  sudo_user: synapse

- name: Synapse systemd job is installed
  template:
    src: synapse.service.j2
    dest: /etc/systemd/system/synapse.service
  notify:
    - reload systemd
    - restart synapse
